const COLORS=['#c8102e','#f0b429','#f7c843','#183b56','#2d8c87','#73b8b2','#8f1026','#245575','#d9a514','#5a8f8b'];
let allFeatures=[], filteredFeatures=[], geoLayer;
let charts={};
const map=L.map('map',{zoomControl:true}).setView([3.2,101.45],9);
const osm=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});
L.control.layers({'Peta':osm,'Satelit':satellite},null,{position:'topleft'}).addTo(map);
L.control.scale({imperial:false}).addTo(map);

const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('ms-MY',{maximumFractionDigits:2}).format(n);
const unique=(arr)=>[...new Set(arr.filter(v=>v!==null&&v!==undefined&&v!==''))].sort((a,b)=>String(a).localeCompare(String(b)));
function colorForCategory(cat){const cats=unique(allFeatures.map(f=>f.properties.KATEGORI));return COLORS[Math.max(0,cats.indexOf(cat))%COLORS.length];}
function populateSelect(id,values){const el=$(id); values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)});}
function groupCount(features,key){const m={};features.forEach(f=>{const v=f.properties[key]??'Tiada Maklumat';m[v]=(m[v]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]);}
function groupSum(features,key,sumKey){const m={};features.forEach(f=>{const v=f.properties[key]??'Tiada Maklumat';m[v]=(m[v]||0)+Number(f.properties[sumKey]||0)});return Object.entries(m).sort((a,b)=>b[1]-a[1]);}
function chartBase(){return {responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{boxWidth:12,font:{size:10}}}},scales:{x:{grid:{color:'#e7edef'},ticks:{font:{size:9}}},y:{grid:{display:false},ticks:{font:{size:9}}}}};}
function renderBar(id,entries,horizontal=true){if(charts[id]) charts[id].destroy();const labels=entries.map(x=>x[0]);const vals=entries.map(x=>x[1]);const options=chartBase();if(horizontal){options.indexAxis='y';}charts[id]=new Chart($(id),{type:'bar',data:{labels,datasets:[{data:vals,backgroundColor:labels.map((_,i)=>COLORS[i%5]),borderRadius:2}]},options:{...options,plugins:{...options.plugins,legend:{display:false}}}});}
function renderDonut(id,entries){if(charts[id]) charts[id].destroy();charts[id]=new Chart($(id),{type:'doughnut',data:{labels:entries.map(x=>x[0]),datasets:[{data:entries.map(x=>x[1]),backgroundColor:entries.map((_,i)=>COLORS[i%COLORS.length]),borderColor:'#fff',borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false,cutout:'58%',plugins:{legend:{position:'right',labels:{boxWidth:10,font:{size:9}}}}}});}
function updateMap(features){if(geoLayer) map.removeLayer(geoLayer);geoLayer=L.geoJSON({type:'FeatureCollection',features},{style:f=>({color:'#fff',weight:.7,fillColor:colorForCategory(f.properties.KATEGORI),fillOpacity:.78}),onEachFeature:(f,l)=>{const p=f.properties;l.bindPopup(`<div class="popup-title">${p.NAMA||'-'}</div><div class="popup-row"><b>Daerah:</b> ${p.DAERAH||'-'}</div><div class="popup-row"><b>PBT:</b> ${p.PBT||'-'}</div><div class="popup-row"><b>Kategori:</b> ${p.KATEGORI||'-'}</div><div class="popup-row"><b>MIP:</b> ${p.MIP==='Yes'?'Ya':p.MIP==='No'?'Tidak':'Tiada Maklumat'}</div><div class="popup-row"><b>Keluasan:</b> ${fmt(p.KELUASAN_HA)} ha</div><div class="popup-row"><b>Alamat:</b> ${p.ALAMAT||'-'}</div>`);}}).addTo(map);$('mapCount').textContent=`${features.length} kawasan`;if(features.length){try{map.fitBounds(geoLayer.getBounds(),{padding:[12,12],maxZoom:12});}catch(e){}}}
function updateKPIs(features){$('kpiKawasan').textContent=features.length;$('kpiPBT').textContent=unique(features.map(f=>f.properties.PBT)).length;$('kpiKategori').textContent=unique(features.map(f=>f.properties.KATEGORI)).length;$('kpiMIP').textContent=features.filter(f=>f.properties.MIP==='Yes').length;}
function renderCharts(features){renderBar('districtChart',groupCount(features,'DAERAH'),true);renderDonut('categoryChart',groupCount(features,'KATEGORI'));renderBar('areaChart',groupSum(features,'DAERAH','KELUASAN_HA'),false);renderBar('pbtChart',groupCount(features,'PBT'),true);const mip=[['MIP',features.filter(f=>f.properties.MIP==='Yes').length],['Bukan MIP',features.filter(f=>f.properties.MIP==='No').length],['Tiada Maklumat',features.filter(f=>!f.properties.MIP).length]];renderDonut('mipChart',mip);$('mipStats').innerHTML=mip.map(x=>`<div class="mip-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')+`<div class="mip-stat"><span>Jumlah ditapis</span><b>${features.length}</b></div>`;}
function renderTable(features){const q=$('searchBox').value.trim().toLowerCase();const rows=features.filter(f=>{const p=f.properties;return !q||[p.NAMA,p.LOKASI,p.ALAMAT,p.DAERAH,p.PBT,p.KATEGORI].some(v=>String(v||'').toLowerCase().includes(q));}).slice(0,300);$('tableBody').innerHTML=rows.map(f=>{const p=f.properties;return `<tr><td>${p.NAMA||'-'}</td><td>${p.DAERAH||'-'}</td><td>${p.PBT||'-'}</td><td>${p.KATEGORI||'-'}</td><td>${p.MIP==='Yes'?'Ya':p.MIP==='No'?'Tidak':'-'}</td><td>${fmt(p.KELUASAN_HA)}</td></tr>`}).join('');}
function applyFilters(){const d=$('filterDaerah').value,p=$('filterPBT').value,k=$('filterKategori').value,m=$('filterMIP').value;filteredFeatures=allFeatures.filter(f=>{const x=f.properties;return (!d||x.DAERAH===d)&&(!p||x.PBT===p)&&(!k||x.KATEGORI===k)&&(!m||(m==='__NULL__'?!x.MIP:x.MIP===m));});updateKPIs(filteredFeatures);renderCharts(filteredFeatures);updateMap(filteredFeatures);renderTable(filteredFeatures);}
async function init(){const data=await fetch('data/perindustrian.geojson').then(r=>r.json());allFeatures=data.features;populateSelect('filterDaerah',unique(allFeatures.map(f=>f.properties.DAERAH)));populateSelect('filterPBT',unique(allFeatures.map(f=>f.properties.PBT)));populateSelect('filterKategori',unique(allFeatures.map(f=>f.properties.KATEGORI)));['filterDaerah','filterPBT','filterKategori','filterMIP'].forEach(id=>$(id).addEventListener('change',applyFilters));$('resetBtn').addEventListener('click',()=>{['filterDaerah','filterPBT','filterKategori','filterMIP'].forEach(id=>$(id).value='');$('searchBox').value='';applyFilters();});$('searchBox').addEventListener('input',()=>renderTable(filteredFeatures));applyFilters();}
init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<div style="position:fixed;bottom:10px;right:10px;background:#fff3cd;border:1px solid #ffe69c;padding:10px;z-index:9999">Data gagal dimuatkan. Jalankan dashboard melalui web server / GitHub Pages.</div>');});
